mutation(
  $sid: String!
  $chineseName: String
  $englishName: String!
  $gender: Gender
  $dateOfBirth: String
  $email: String
  $phone: String
  $college: College!
  $major: String!
  $dateOfEntry: String!
  $expectedGraduationDate: String!
) {
  newPerson(
    input: {
      data: {
        sid: $sid
        chineseName: $chineseName
        englishName: $englishName
        gender: $gender
        dateOfBirth: $dateOfBirth
        email: $email
        phone: $phone
        college: $college
        major: $major
        dateOfEntry: $dateOfEntry
        expectedGraduationDate: $expectedGraduationDate
      }
    }
  ) {
    success
    message
    person {
      id
      sid
      chineseName
      englishName
      gender
      dateOfBirth
      email
      phone
      college
      dateOfEntry
      expectedGraduationDate
      memberSince
      major
    }
  }
}
