query people {
  person {
    id
    sid
    chineseName
    englishName
    gender
    dateOfBirth
    email
    phone
    college
    dateOfEntry
    expectedGraduationDate
    memberSince
    memberUntil
    major {
      code
    }
  }
}
