query {
  people {
    id
    sid
    chineseName
    englishName
    gender
    dateOfBirth
    email
    phone
    dateOfEntry
    expectedGraduationDate
    memberSince
    memberUntil
    status
    registrationType
    updatedAt
    major {
      code
      chineseName
      englishName
    }
    college {
      code
      chineseName
      englishName
    }
  }
}
