query {
  people {
    id
    sid
    chineseName
    englishName
    gender
    dateOfBirth
    email
    phone
    college {
      code
    }
    dateOfEntry
    expectedGraduationDate
    memberSince
    memberUntil
    major {
      code
    }
  }
}
