mutation($sid: String!, $nickname: String, $pos: String) {
  newExecutive(sid: $sid, nickname: $nickname, pos: $pos) {
    success
    message
    executive {
      id
      sid
      nickname
      pos
    }
  }
}
